import { Geist, Geist_Mono } from "next/font/google";
import './variables.sass'
import './globals.sass'
import './globals.css'
import Sidebar from "./components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body>
        <main style={{display: 'flex'}}>
          <Sidebar/>
          {children}
        </main>
      </body>
    </html>
  );
}
